In [1]:
# Base Data Science snippet
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import time
from tqdm import tqdm_notebook

%matplotlib inline
%load_ext autoreload
%autoreload 2

In [31]:
%%time
from simulations.chicken_game import *
agents = [Player(i) for i in range(10)]

Wall time: 0 ns


In [32]:
agents

[Player(id=0, status=0, x=4),
 Player(id=1, status=0, x=58),
 Player(id=2, status=0, x=15),
 Player(id=3, status=0, x=78),
 Player(id=4, status=0, x=83),
 Player(id=5, status=0, x=71),
 Player(id=6, status=0, x=22),
 Player(id=7, status=0, x=73),
 Player(id=8, status=0, x=43),
 Player(id=9, status=0, x=34)]

In [33]:
env = ChickenGame(agents)

In [34]:
xs = env["x"]

In [35]:
from scipy.spatial import distance

In [36]:
xsa = np.concatenate([xs[:,np.newaxis],np.zeros((len(xs),1))],axis = 1)

In [37]:
from sklearn.neighbors import NearestNeighbors

In [64]:
nn = NearestNeighbors(metric = "euclidean",n_neighbors = 5,radius = 100)

In [65]:
nn.fit(xsa)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='euclidean',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=100)

In [67]:
%%time
distance,ind = nn.kneighbors(xsa)

Wall time: 998 µs


In [72]:
ind

array([[0, 2, 6, 9, 8],
       [1, 5, 7, 8, 3],
       [2, 6, 0, 9, 8],
       [3, 7, 4, 5, 1],
       [4, 3, 7, 5, 1],
       [5, 7, 3, 4, 1],
       [6, 2, 9, 0, 8],
       [7, 5, 3, 4, 1],
       [8, 9, 1, 6, 2],
       [9, 8, 6, 2, 1]], dtype=int64)

(array([], dtype=int64), array([], dtype=int64))

In [76]:
np.where(distance < 20)

(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5,
        5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 9, 9, 9, 9], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2,
        3, 4, 0, 1, 2, 3, 0, 1, 2, 3, 4, 0, 1, 2, 0, 1, 2, 3], dtype=int64))

In [75]:
ind[*np.where(distance < 20)]

SyntaxError: invalid syntax (<ipython-input-75-2a0c44e637dd>, line 1)

In [56]:
%%time
interactions = env.interactions()

Wall time: 0 ns


In [57]:
%%time
xs = env.get("x")

Wall time: 0 ns


In [72]:
xs

array([42, 78, 32, ..., 13, 21, 95])

In [19]:
render = []
statuses = []
for i in tqdm_notebook(range(100)):
    env.step()
    render.append(env.render())
    statuses.append(env.get("status"))
#     print(len(env.agents),env.render())

HBox(children=(IntProgress(value=0), HTML(value='')))

In [20]:
test = pd.concat(statuses,axis = 1).T